---
title: "week4_part1"
author: "Andrea Gracia"
date: "10/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Confidence Intervals associated with a sample

```{r}
otter_length <- c(38,41,50, 27,32,41,48,60,43)

t.test(otter_length)


```

## T-test (1-sample t-test)

See a claim: mean otter length is 50 inches
```{r}
otter_test <- t.test(x=otter_length, mu=50)
otter_test
```

## Two-sample t-test
```{r}
desert_bighorns <- c(32,44,18,26,50,33,42,40)
sierra_bighorns<- c(28,31,40,42,26,29,31)

t.test(x=desert_bighorns, y=sierra_bighorns)
```

## Part 2: Two sample t-test

```{r}
library(tidyverse)
View(mpg)
```

Interested in SUV and compact cars 

```{r}
compact_suv <- mpg %>% 
  filter(class %in% c("compact", "suv"))
```

### Exploratory data viz

Histograms

```{r}
ggplot(data=compact_suv, aes(x=cty))+
  geom_histogram(bins=15) + 
  facet_wrap(~class)
```

### Quantile-quantile 
```{r}
ggplot(data = compact_suv, aes(sample=cty)) +
  geom_qq()+
  facet_wrap(~class)
```
### Descriptive statistics

```{r}
car_stats <- compact_suv %>% 
  group_by(class) %>% 
  summarise(mean_city=mean(cty),
            sd_cty=sd(cty),
            n=n()) #calculate number of obs

car_stats
```

### 2-sample t-test

create vectors containing observations for each sample (city gas mileage)

```{r}
compact_sample <- compact_suv %>% 
  filter(class=="compact") %>% 
  pull(cty) #makes into vector

suv_sample <- compact_suv %>% 
  filter(class=="suv") %>% 
  pull(cty)

t.test(x=compact_sample, suv_sample)
```


